In [40]:
! pip install scikit-sos

Requirement already satisfied: scikit-sos in /Users/Bellerofonte/opt/anaconda3/lib/python3.7/site-packages (0.1.10)
Requirement already satisfied: numpy in /Users/Bellerofonte/opt/anaconda3/lib/python3.7/site-packages (from scikit-sos) (1.19.5)

In [41]:
from sksos import SOS

In [44]:
detector = SOS(perplexity=10)

In [46]:
from sklearn.datasets import load_iris

In [48]:
iris = load_iris()

In [50]:
detector.predict(iris.data)

array([0.12475767, 0.2221408 , 0.2729049 , 0.26433906, 0.21360964,
       0.32433357, 0.43725563, 0.1309091 , 0.33790929, 0.24610288,
       0.13844235, 0.32335619, 0.3361014 , 0.67691646, 0.71382075,
       0.71018363, 0.4694586 , 0.15807089, 0.5987628 , 0.15551077,
       0.59725344, 0.30294747, 0.95542176, 0.49410534, 0.8738878 ,
       0.58494387, 0.22547518, 0.17694403, 0.23495951, 0.23303823,
       0.23968847, 0.45175777, 0.60245556, 0.28422769, 0.15634078,
       0.71690899, 0.64807364, 0.48595033, 0.24227873, 0.13866319,
       0.36544338, 0.98100351, 0.41552454, 0.58518839, 0.7778504 ,
       0.36634329, 0.25224144, 0.12674374, 0.15198224, 0.23252425,
       0.56495645, 0.2943375 , 0.26949059, 0.3765338 , 0.33797668,
       0.38428453, 0.35995996, 0.34677959, 0.22298808, 0.56250566,
       0.66571891, 0.49254749, 0.8211221 , 0.17266524, 0.67149184,
       0.33680924, 0.29240198, 0.42632151, 0.39062045, 0.18029998,
       0.44783675, 0.59306797, 0.30164949, 0.53868675, 0.31710413,
       0.20592675, 0.48596771, 0.49074264, 0.28229222, 0.54310423,
       0.1910655 , 0.28832567, 0.15082038, 0.24909337, 0.36883065,
       0.71388206, 0.24743678, 0.4162199 , 0.31174181, 0.17362792,
       0.46052121, 0.16510183, 0.12964583, 0.27951394, 0.17194609,
       0.29131895, 0.11182104, 0.29002317, 0.66270548, 0.13655859,
       0.76565737, 0.15358419, 0.31504322, 0.2780622 , 0.34753526,
       0.27541564, 0.96436807, 0.29570303, 0.81984205, 0.72425447,
       0.32187879, 0.39029451, 0.20124616, 0.48841271, 0.83161004,
       0.36541458, 0.19831928, 0.48674184, 0.65472271, 0.75521907,
       0.14147233, 0.48091373, 0.32113783, 0.14315917, 0.3281312 ,
       0.25818276, 0.24021536, 0.18619552, 0.16272878, 0.49729756,
       0.24869287, 0.51412434, 0.23519303, 0.3076284 , 0.89797017,
       0.53441759, 0.32798975, 0.27014974, 0.18022398, 0.24933408,
       0.22261852, 0.51316327, 0.15358419, 0.17638303, 0.28008082,
       0.31951804, 0.43288611, 0.17731039, 0.36475409, 0.41850679])

In [52]:
import pandas as pd

In [16]:
df = pd.DataFrame(data = iris.data, columns = iris.feature_names)

In [18]:
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [20]:
df["outlier"] = detector.predict(df.values)

In [22]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),outlier
0,5.1,3.5,1.4,0.2,0.124758
1,4.9,3.0,1.4,0.2,0.222141
2,4.7,3.2,1.3,0.2,0.272905
3,4.6,3.1,1.5,0.2,0.264339
4,5.0,3.6,1.4,0.2,0.213610

In [24]:
df.sort_values("outlier", ascending=False)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),outlier
41,4.5,2.3,1.3,0.3,0.981004
106,4.9,2.5,4.5,1.7,0.964368
22,4.6,3.6,1.0,0.2,0.955422
134,6.1,2.6,5.6,1.4,0.897970
24,4.8,3.4,1.9,0.2,0.873888
...,...,...,...,...,...
7,5.0,3.4,1.5,0.2,0.130909
92,5.8,2.6,4.0,1.2,0.129646
47,4.6,3.2,1.4,0.2,0.126744
0,5.1,3.5,1.4,0.2,0.124758
96,5.7,2.9,4.2,1.3,0.111821

In [26]:
from sklearn.decomposition import PCA

In [27]:
X = df.drop("outlier", axis = 1).values
X = df.values[:,0:4]
X = iris.data

In [30]:
pca = PCA(n_components=2)
X_map = pca.fit_transform(X)

In [32]:
df["x"] = X_map[:,0]
df["y"] = X_map[:,1]

In [36]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),outlier,x,y
0,5.1,3.5,1.4,0.2,0.124758,-2.684126,0.319397
1,4.9,3.0,1.4,0.2,0.222141,-2.714142,-0.177001
2,4.7,3.2,1.3,0.2,0.272905,-2.888991,-0.144949
3,4.6,3.1,1.5,0.2,0.264339,-2.745343,-0.318299
4,5.0,3.6,1.4,0.2,0.213610,-2.728717,0.326755

http://jeroenjanssens.com/2013/11/24/stochastic-outlier-selection.html